/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorNotas;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.HiloEstadisticas;
import modelo.HiloInscripciones;
import modelo.HiloSesionesActivas;
import modelo.Nota;

/**
 *
 * @author emily
 */
public class PanelInstructor extends javax.swing.JPanel {

    private VentanaPrincipal ventanaPrincipal;
    private HiloSesionesActivas tareaSesiones;
    private HiloInscripciones tareaInscripciones;
    private HiloEstadisticas tareaEstadisticas;

    private Thread hiloSesiones;
    private Thread hiloInscripciones;
    private Thread hiloEstadisticas;

    private boolean hilosIniciados;

    /**
     * Creates new form PanelInstructor
     */
    public PanelInstructor(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        this.hilosIniciados = false;
        initComponents();

        // Configuramos las tablas con sus encabezados correctos
        configurarTablaNotas();
        configurarTablaCursosInstructor();

        llenarTablaNotas();
    }

    //iniciamos lo hilos para que se muestren en pantalla
    public void iniciarHilos() {
        if (hilosIniciados) {
            return;
        }
        //ponemos mensaje en el areatezt
        areaConsola.setText("Iniciando Monitoreo de Hilos...\n");

        // mostramos llamando a hilos en modelos
        tareaSesiones = new HiloSesionesActivas(areaConsola, ventanaPrincipal.getControlador());
        hiloSesiones = new Thread(tareaSesiones);
        hiloSesiones.start();
        // mostramos llamando a hilos en modelos

        tareaInscripciones = new HiloInscripciones(areaConsola, ventanaPrincipal.getControlador());
        hiloInscripciones = new Thread(tareaInscripciones);
        hiloInscripciones.start();
        // mostramos llamando a hilos en modelos

        tareaEstadisticas = new HiloEstadisticas(areaConsola, ventanaPrincipal.getControlador());
        hiloEstadisticas = new Thread(tareaEstadisticas);
        hiloEstadisticas.start();

        // Llenamos la tabla de cursos ahora que ya sabemos quien esta logueado
        llenarTablaCursosInstructor();

        hilosIniciados = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaConsola = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scrollTabla1 = new javax.swing.JScrollPane();
        tablaCursosInstructor = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnActualizarNota = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnEliminarNota = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCodigoSeccion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        txtNota = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCodigoEstudiante = new javax.swing.JTextField();
        btnCrearNota = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtPonderacion = new javax.swing.JTextField();
        btnCsvNotas = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnExportarNotas = new javax.swing.JButton();
        scrollTabla = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtFiltroCurso = new javax.swing.JTextField();
        txtFiltroSeccion = new javax.swing.JTextField();
        txtFiltroEstudiante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        btnLimpiarFiltros = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("INSTRUCTOR");

        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCerrar))
                .addGap(16, 16, 16))
        );

        areaConsola.setColumns(20);
        areaConsola.setRows(5);
        jScrollPane1.setViewportView(areaConsola);

        jLabel2.setText("CURSOS ASIGNADOS");

        tablaCursosInstructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCursosInstructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCursosInstructorMouseClicked(evt);
            }
        });
        scrollTabla1.setViewportView(tablaCursosInstructor);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabla1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(304, 304, 304)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(scrollTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cursos", jPanel2);

        btnActualizarNota.setText("Actualizar");
        btnActualizarNota.addActionListener(this::btnActualizarNotaActionPerformed);

        jLabel16.setText("Codigo Estudiante");

        btnEliminarNota.setText("Eliminar");
        btnEliminarNota.addActionListener(this::btnEliminarNotaActionPerformed);

        jLabel17.setText("CREAR NOTAS");

        jLabel18.setText("Ponderacion %");

        txtCodigoSeccion.addActionListener(this::txtCodigoSeccionActionPerformed);

        jLabel19.setText("Nota (0 - 100)");

        jLabel14.setText("Codigo Curso");

        btnCrearNota.setText("Crear");
        btnCrearNota.addActionListener(this::btnCrearNotaActionPerformed);

        jLabel15.setText("Codigo Seccion");

        btnCsvNotas.setText("csv Notas");
        btnCsvNotas.addActionListener(this::btnCsvNotasActionPerformed);

        jLabel20.setText("Fecha registro");

        btnExportarNotas.setText("exportar notas");
        btnExportarNotas.addActionListener(this::btnExportarNotasActionPerformed);

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaNotasMouseClicked(evt);
            }
        });
        scrollTabla.setViewportView(tablaNotas);

        jLabel3.setText("Filtrar por:");

        jLabel4.setText("Estudiante:");

        jLabel5.setText("Seccion");

        jLabel6.setText("Curso");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(this::btnFiltrarActionPerformed);

        btnLimpiarFiltros.setText("Limpiar Filtros");
        btnLimpiarFiltros.addActionListener(this::btnLimpiarFiltrosActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPonderacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCrearNota)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarNota)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarNota))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCsvNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFiltroEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFiltroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFiltroSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtCodigoSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFiltroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFiltroSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFiltroEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFiltrar)
                            .addComponent(btnLimpiarFiltros))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtCodigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPonderacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearNota)
                            .addComponent(btnActualizarNota)
                            .addComponent(btnEliminarNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCsvNotas)
                            .addComponent(btnExportarNotas))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Notas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        ventanaPrincipal.cerrarSesion();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnActualizarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarNotaActionPerformed
        // Obtiene los datos desde los campos de la interfaz
        String codigoCurso = txtCodigoCurso.getText().trim();
        String codigoSeccion = txtCodigoSeccion.getText().trim();
        String codigoEstudiante = txtCodigoEstudiante.getText().trim();
        String ponderacionTexto = txtPonderacion.getText().trim();
        String notaTexto = txtNota.getText().trim();
        String fecha = txtFecha.getText().trim();

        // Valida que ningun campo este vacio
        if (codigoCurso.isEmpty() || codigoSeccion.isEmpty() || codigoEstudiante.isEmpty()
                || ponderacionTexto.isEmpty() || notaTexto.isEmpty() || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios para actualizar.");
            return;
        }

        // Valida que la ponderacion sea un numero decimal
        double ponderacion;
        try {
            ponderacion = Double.parseDouble(ponderacionTexto);
            if (ponderacion <= 0) {
                JOptionPane.showMessageDialog(this, "La ponderacion debe ser mayor a 0.");
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El campo Ponderacion debe ser un numero.");
            return;
        }

        // Valida que la nota sea un numero decimal en rango valido
        double nota;
        try {
            nota = Double.parseDouble(notaTexto);
            if (nota < 0 || nota > 100) {
                JOptionPane.showMessageDialog(this, "La nota debe estar entre 0 y 100.");
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El campo Nota debe ser un numero.");
            return;
        }

        // Llama al controlador para actualizar la nota
        boolean actualizado = ventanaPrincipal.getControladorNotas()
                .actualizarNota(codigoCurso, codigoSeccion, codigoEstudiante, ponderacion, nota, fecha);

        // Si se actualizo correctamente
        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Nota actualizada correctamente.");

            // Recarga la tabla con los datos actualizados
            llenarTablaNotas();

            // Limpia los campos del formulario
            limpiarCamposNotas();

            // Guarda los cambios en archivo
            ventanaPrincipal.getControlador().guardarSistema();

        } else {
            JOptionPane.showMessageDialog(this, "No se encontro la nota a actualizar.");
        }
    }//GEN-LAST:event_btnActualizarNotaActionPerformed

    private void btnEliminarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNotaActionPerformed
        // Pedimos los tres codigos que identifican la nota, igual que se pide el codigo al eliminar instructor
        String codigoCurso = JOptionPane.showInputDialog(this, "Ingrese el codigo del curso:");
        if (codigoCurso == null || codigoCurso.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el codigo del curso.");
            return;
        }

        String codigoSeccion = JOptionPane.showInputDialog(this, "Ingrese el codigo de la seccion:");
        if (codigoSeccion == null || codigoSeccion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el codigo de la seccion.");
            return;
        }

        String codigoEstudiante = JOptionPane.showInputDialog(this, "Ingrese el codigo del estudiante:");
        if (codigoEstudiante == null || codigoEstudiante.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el codigo del estudiante.");
            return;
        }

        // Llamamos al controlador para intentar eliminar la nota
        boolean eliminado = ventanaPrincipal.getControladorNotas()
                .eliminarNota(codigoCurso.trim(), codigoSeccion.trim(), codigoEstudiante.trim());

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Nota eliminada correctamente.");
            llenarTablaNotas();
            limpiarCamposNotas();
            ventanaPrincipal.getControlador().guardarSistema();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro una nota con esos datos.");
        }
    }//GEN-LAST:event_btnEliminarNotaActionPerformed

    private void txtCodigoSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoSeccionActionPerformed

    private void btnCrearNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNotaActionPerformed
        // Leemos todos los campos del formulario
        String codigoCurso = txtCodigoCurso.getText().trim();
        String codigoSeccion = txtCodigoSeccion.getText().trim();
        String codigoEstudiante = txtCodigoEstudiante.getText().trim();
        String ponderacionTexto = txtPonderacion.getText().trim();
        String notaTexto = txtNota.getText().trim();
        String fecha = txtFecha.getText().trim();

        // Verificamos que ningun campo este vacio
        if (codigoCurso.isEmpty() || codigoSeccion.isEmpty() || codigoEstudiante.isEmpty()
                || ponderacionTexto.isEmpty() || notaTexto.isEmpty() || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        // Verificamos que el curso con esa seccion exista en el sistema
        if (!existeCursoSeccion(codigoCurso, codigoSeccion)) {
            JOptionPane.showMessageDialog(this, "No existe un curso con ese codigo y seccion.");
            return;
        }

        // Verificamos que ese curso le pertenezca al instructor que esta en sesion
        if (!cursoPerteneceAlInstructor(codigoCurso, codigoSeccion)) {
            JOptionPane.showMessageDialog(this, "No tienes permiso para registrar notas en ese curso.");
            return;
        }

        // Convertimos ponderacion a numero decimal
        double ponderacion;
        try {
            ponderacion = Double.parseDouble(ponderacionTexto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La ponderacion debe ser un numero (ejemplo: 30.0).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertimos nota a numero decimal
        double nota;
        try {
            nota = Double.parseDouble(notaTexto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La nota debe ser un numero (ejemplo: 85.5).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Creamos el objeto Nota y pedimos al controlador que lo guarde
        Nota nuevaNota = new Nota(codigoCurso, codigoSeccion, codigoEstudiante, ponderacion, nota, fecha);
        ControladorNotas controladorNotas = ventanaPrincipal.getControladorNotas();
        boolean creado = controladorNotas.agregarNota(nuevaNota);

        if (creado) {
            // Calculamos el promedio actualizado del estudiante
            double promedio = controladorNotas.calcularPromedio(codigoEstudiante, codigoSeccion);
            String mensajePromedio = String.format("Promedio ponderado de %s en seccion %s: %.2f", codigoEstudiante, codigoSeccion, promedio);
            JOptionPane.showMessageDialog(this, "Nota creada correctamente.\n" + mensajePromedio, "Exito", JOptionPane.INFORMATION_MESSAGE);
            llenarTablaNotas();
            limpiarCamposNotas();
            ventanaPrincipal.getControlador().guardarSistema();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear la nota.\n"
                    + "Posibles causas:\n"
                    + "- El codigo de estudiante no existe en el sistema.\n"
                    + "- Ya existe una nota para este estudiante en este curso/seccion.\n"
                    + "- Ponderacion debe ser mayor a 0.\n"
                    + "- Nota debe estar entre 0 y 100.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearNotaActionPerformed

    private void btnCsvNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCsvNotasActionPerformed
        cargarCsvNotas();
    }//GEN-LAST:event_btnCsvNotasActionPerformed

    private void btnExportarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarNotasActionPerformed
        exportarCsvNotas();
    }//GEN-LAST:event_btnExportarNotasActionPerformed

    private void tablaNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaNotasMouseClicked
        int fila = tablaNotas.getSelectedRow();
        // Carga los datos de la fila seleccionada en los campos del formulario
        if (fila != -1) {
            txtCodigoCurso.setText(tablaNotas.getValueAt(fila, 0).toString());
            txtCodigoSeccion.setText(tablaNotas.getValueAt(fila, 1).toString());
            txtCodigoEstudiante.setText(tablaNotas.getValueAt(fila, 2).toString());
            txtPonderacion.setText(tablaNotas.getValueAt(fila, 3).toString());
            txtNota.setText(tablaNotas.getValueAt(fila, 4).toString());
            txtFecha.setText(tablaNotas.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_tablaNotasMouseClicked

    private void tablaCursosInstructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursosInstructorMouseClicked
        int fila = tablaCursosInstructor.getSelectedRow();
        // Cuando el instructor hace clic en un curso, llenamos los campos de notas
        // para que no tenga que escribir el codigo y seccion manualmente
        if (fila != -1) {
            txtCodigoCurso.setText(tablaCursosInstructor.getValueAt(fila, 0).toString());
            txtCodigoSeccion.setText(tablaCursosInstructor.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_tablaCursosInstructorMouseClicked

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        filtrarTablaNotas();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnLimpiarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltrosActionPerformed
        // Borramos lo que habia en los campos de filtro
        txtFiltroCurso.setText("");
        txtFiltroSeccion.setText("");
        txtFiltroEstudiante.setText("");
        // Volvemos a mostrar todas las notas sin filtro
        llenarTablaNotas();
    }//GEN-LAST:event_btnLimpiarFiltrosActionPerformed

    // Configura los encabezados de la tabla de cursos del instructor
    private void configurarTablaCursosInstructor() {
        DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"Codigo", "Nombre", "Descripcion", "Creditos", "Seccion"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaCursosInstructor.setModel(modelo);
    }

    // Muestra solo los cursos asignados al instructor que tiene la sesion activa
    private void llenarTablaCursosInstructor() {
        DefaultTableModel tabla = (DefaultTableModel) tablaCursosInstructor.getModel();
        tabla.setRowCount(0);

        modelo.Curso[] cursos = ventanaPrincipal.getControladorCursos().getCursos();
        int cantidad = ventanaPrincipal.getControladorCursos().getCantidadCursos();
        modelo.Usuario usuarioActual = ventanaPrincipal.getControlador().getUsuarioActual();

        if (usuarioActual == null) {
            return;
        }

        for (int i = 0; i < cantidad; i++) {
            modelo.Curso curso = cursos[i];
            // Solo mostramos los cursos cuyo codigoInstructor coincide con el usuario en sesion
            if (curso.getCodigoInstructor().equals(usuarioActual.getCodigo())) {
                tabla.addRow(new Object[]{
                    curso.getCodigo(),
                    curso.getNombre(),
                    curso.getDescripcion(),
                    curso.getCreditos(),
                    curso.getSeccion()
                });
            }
        }
    }

    // Verifica que exista un curso con ese codigo y esa seccion en el sistema
    private boolean existeCursoSeccion(String codigoCurso, String seccion) {
        modelo.Curso[] cursos = ventanaPrincipal.getControladorCursos().getCursos();
        int cantidad = ventanaPrincipal.getControladorCursos().getCantidadCursos();

        for (int i = 0; i < cantidad; i++) {
            modelo.Curso curso = cursos[i];
            if (curso.getCodigo().equals(codigoCurso)
                    && curso.getSeccion().equals(seccion)) {
                return true;
            }
        }
        return false;
    }

    // Verifica que el curso pertenezca al instructor que esta usando el sistema ahora mismo
    private boolean cursoPerteneceAlInstructor(String codigoCurso, String seccion) {
        modelo.Usuario usuarioActual = ventanaPrincipal.getControlador().getUsuarioActual();

        if (usuarioActual == null) {
            return false;
        }

        modelo.Curso[] cursos = ventanaPrincipal.getControladorCursos().getCursos();
        int cantidad = ventanaPrincipal.getControladorCursos().getCantidadCursos();

        for (int i = 0; i < cantidad; i++) {
            modelo.Curso curso = cursos[i];
            if (curso.getCodigo().equals(codigoCurso)
                    && curso.getSeccion().equals(seccion)
                    && curso.getCodigoInstructor().equals(usuarioActual.getCodigo())) {
                return true;
            }
        }
        return false;
    }

    // Configura la tabla con los encabezados correctos para mostrar notas
    // Ahora incluye Promedio y Estado ademas de los datos basicos
    private void configurarTablaNotas() {
        DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"Codigo Curso", "Seccion", "Estudiante", "Ponderacion", "Nota", "Fecha", "Promedio", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // La tabla no se edita directamente, solo con los campos del formulario
            }
        };
        tablaNotas.setModel(modelo);
    }

    // Recorre todas las notas guardadas y las muestra en la tabla sin ningun filtro
    private void llenarTablaNotas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaNotas.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla antes de volver a llenarla

        ControladorNotas controladorNotas = ventanaPrincipal.getControladorNotas();
        Nota[] notas = controladorNotas.getNotas();
        int cantidad = controladorNotas.getCantidadNotas();

        // Agregamos cada nota a la tabla usando el metodo auxiliar
        for (int i = 0; i < cantidad; i++) {
            agregarFilaEnTabla(modelo, notas[i]);
        }
    }

    // Filtra la tabla de notas segun lo que el instructor escribio en los campos de filtro
    // Si un campo de filtro esta vacio, no se aplica ese filtro
    private void filtrarTablaNotas() {
        // Leemos los filtros y los pasamos a minusculas para comparar sin importar mayusculas
        String filtroCurso = txtFiltroCurso.getText().trim().toLowerCase();
        String filtroSeccion = txtFiltroSeccion.getText().trim().toLowerCase();
        String filtroEstudiante = txtFiltroEstudiante.getText().trim().toLowerCase();

        DefaultTableModel modelo = (DefaultTableModel) tablaNotas.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla para volver a llenar con lo filtrado

        ControladorNotas controladorNotas = ventanaPrincipal.getControladorNotas();
        Nota[] notas = controladorNotas.getNotas();
        int cantidad = controladorNotas.getCantidadNotas();

        for (int i = 0; i < cantidad; i++) {
            Nota n = notas[i];

            // Verificamos si la nota coincide con cada filtro
            // Si el filtro esta vacio, esa condicion siempre es verdadera
            boolean coincideCurso = filtroCurso.isEmpty()
                    || n.getCodigoCurso().toLowerCase().contains(filtroCurso);
            boolean coincideSeccion = filtroSeccion.isEmpty()
                    || n.getCodigoSeccion().toLowerCase().contains(filtroSeccion);
            boolean coincideEstudiante = filtroEstudiante.isEmpty()
                    || n.getCodigoEstudiante().toLowerCase().contains(filtroEstudiante);

            // Solo agregamos la nota si cumple los tres filtros al mismo tiempo
            if (coincideCurso && coincideSeccion && coincideEstudiante) {
                agregarFilaEnTabla(modelo, n);
            }
        }
    }

    // Metodo auxiliar que calcula el promedio y estado de una nota y agrega la fila a la tabla
    // Se usa en llenarTablaNotas y filtrarTablaNotas para no repetir el mismo codigo
    private void agregarFilaEnTabla(DefaultTableModel modelo, Nota n) {
        ControladorNotas controladorNotas = ventanaPrincipal.getControladorNotas();

        // Calculamos el promedio ponderado del estudiante en esa seccion
        double promedio = controladorNotas.calcularPromedio(n.getCodigoEstudiante(), n.getCodigoSeccion());

        String promedioTexto;
        String estado;

        if (promedio < 0) {
            // calcularPromedio devuelve -1 cuando no hay notas todavia
            promedioTexto = "N/A";
            estado = "N/A";
        } else {
            // Formateamos el promedio con dos decimales
            promedioTexto = String.format("%.2f", promedio);
            // Aprobado si el promedio es 61 o mas, Reprobado si es menos
            estado = promedio >= 61 ? "Aprobado" : "Reprobado";
        }

        modelo.addRow(new Object[]{
            n.getCodigoCurso(),
            n.getCodigoSeccion(),
            n.getCodigoEstudiante(),
            n.getPonderacion(),
            n.getNota(),
            n.getFechaRegistro(),
            promedioTexto,
            estado
        });
    }

    // Deja todos los campos del formulario vacios despues de una operacion
    private void limpiarCamposNotas() {
        txtCodigoCurso.setText("");
        txtCodigoSeccion.setText("");
        txtCodigoEstudiante.setText("");
        txtPonderacion.setText("");
        txtNota.setText("");
        txtFecha.setText("");
    }

    // Abre un selector de archivos para elegir un CSV e importar notas
    private void cargarCsvNotas() {
        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Seleccionar archivo CSV de notas");
        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = selector.getSelectedFile();
            // El controlador muestra el mensaje de exito o error internamente
            ventanaPrincipal.getControladorNotas().cargarNotasCSV(archivo.getAbsolutePath());
            llenarTablaNotas();
            ventanaPrincipal.getControlador().guardarSistema();
        }
    }

    // Abre un selector para elegir donde guardar el CSV exportado
    private void exportarCsvNotas() {
        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Guardar archivo CSV de notas");
        selector.setSelectedFile(new File("notas_exportadas.csv"));
        int resultado = selector.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = selector.getSelectedFile();
            String reporte = ventanaPrincipal.getControladorNotas().exportarNotasCSV(archivo.getAbsolutePath());
            JOptionPane.showMessageDialog(this, reporte, "Resultado de exportacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaConsola;
    private javax.swing.JButton btnActualizarNota;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrearNota;
    private javax.swing.JButton btnCsvNotas;
    private javax.swing.JButton btnEliminarNota;
    private javax.swing.JButton btnExportarNotas;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiarFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JScrollPane scrollTabla1;
    private javax.swing.JTable tablaCursosInstructor;
    private javax.swing.JTable tablaNotas;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextField txtCodigoEstudiante;
    private javax.swing.JTextField txtCodigoSeccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFiltroCurso;
    private javax.swing.JTextField txtFiltroEstudiante;
    private javax.swing.JTextField txtFiltroSeccion;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPonderacion;
    // End of variables declaration//GEN-END:variables
}
