/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.AppController;
import controlador.ControladorCursos;
import controlador.ControladorNotas;
import controlador.ControladorSerializacion;
import controlador.ControladorUsuarios;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import modelo.Listas;

/**
 *
 * @author emily
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private AppController controlador;
    private ControladorUsuarios controladorUsuarios;
    private ControladorCursos controladorCursos;
    private ControladorNotas controladorNotas;
    private CardLayout cardLayout;// CardLayout permite cambiar entre diferentes paneles
    private JPanel panelPrincipal;

    private PanelAdministrador panelAdministrador;
    private PanelInstructor panelInstructor;
    private PanelLogin panelLogin;
    private PanelEstudiante panelEstudiante;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        // Carga los datos guardados desde el archivo
        Listas lista = ControladorSerializacion.cargarListas();
        this.controlador = new AppController(lista);
        this.controladorUsuarios = new ControladorUsuarios(lista);
        this.controladorCursos = new ControladorCursos(lista); // Controlador especifico para operaciones de cursos
        this.controladorNotas = new ControladorNotas(lista); // Controlador especifico para operaciones de notas
        //Configuracion de la ventana
        this.cardLayout = new CardLayout(); // Crea el CardLayout
        this.panelPrincipal = new JPanel(cardLayout);

        //Registro de vistas
        // INICIALIZAR TODOS LOS PANELES
        this.panelLogin = new PanelLogin(this);
        this.panelAdministrador = new PanelAdministrador(this);
        this.panelInstructor = new PanelInstructor(this);
        this.panelEstudiante = new PanelEstudiante(this);

        // AGREGARLOS AL CARDLAYOUT
        panelPrincipal.add(panelLogin, "Login");
        panelPrincipal.add(panelAdministrador, "Administrador");
        panelPrincipal.add(panelInstructor, "Instructor");
        panelPrincipal.add(panelEstudiante, "Estudiante");

        add(panelPrincipal);  // Agrega el panel principal a la ventana
        pack();  // Ajusta el tamaño de la ventana al contenido
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    //cambiar de una vista a otra
    public void cambiarVista(String nombreVista) {
// Muestra el panel que tenga el nombre indicado
        cardLayout.show(panelPrincipal, nombreVista);

        if ("Administrador".equals(nombreVista)) {
            panelAdministrador.iniciarHilos();
        } else if ("Instructor".equals(nombreVista)) {
            panelInstructor.iniciarHilos();
        } else if ("Estudiante".equals(nombreVista)) {
            // Llenamos las tablas del estudiante ahora que ya sabemos quien esta logueado
            panelEstudiante.inicializar();
        }
    }

    public AppController getControlador() {
        return controlador;
    }

    public ControladorUsuarios getControladorUsuarios() {
        return controladorUsuarios;
    }

    public ControladorCursos getControladorCursos() {
        return controladorCursos;
    }

    public ControladorNotas getControladorNotas() {
        return controladorNotas;
    }

    public void cerrarSesion() {
        controlador.disminuirUsuariosActivos();  // Disminuye la cantidad de usuarios activos
        controlador.guardarSistema(); // Guarda el sistema antes de volver al login
        cambiarVista("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
